### PR TITLE
Add gsum/gcount to GaugeHistogram.

### PR DESCRIPTION
**Pull request by brian-brazil**
Allow gsum, gcount, and created to be sanely returned in Prometheus
format.

Extend openmetrics parser unittests to cover Info and StateSet.

@SuperQ

### CODE REVIEW

**Comment by SuperQ** [comment]
Can you link to the OpenMetrics specs here for reference?

**Comment by brian-brazil** [comment]
https://docs.google.com/document/d/1KwV0mAXwwbvvifBvDKH_LU1YjyXE_wxCkHNoCGq1GX0/edit#heading=h.1cvzqd4ksd23 is the relevant bit in the draft.

**Comment by brian-brazil** [comment]
I did a bit more work on other nitty aspects in the spec, and added them in here.

**Comment by RichiH** [comment]
LGTM

**Pull request merged**
