### PR TITLE
Float histograms

### LINKED ISSUE #345: Histogram buckets do not follow OpenMetrics specification
OpenMetrics draft specifies the default Go %g format. 

Python is adding decimal number to the `le` field.

Like this:
```
request_duration_seconds_bucket{code="200",endpoint="/batch_read",le="1.0",method="GET",type="REST"} 545729.0
```

the `le` should be `le="1"`

This causes problems when comparing metrics with i.e. golang exported metrics

More about this https://github.com/prometheus/client_golang/issues/500

### PR DESCRIPTION
**Pull request by brian-brazil**
Fixes #345

### CODE REVIEW

**Comment by tivvit** [comment]
wow cool thanks for the speed!

**Comment by tivvit** [comment]
I think that it looks ok, but I do not know the codebase much and I do not have the rights to merge it. Who would be the best person to merge this @brian-brazil?

**Comment by brian-brazil** [comment]
There's more work to be done here, it looks like we're going the other way on this.

**Comment by brian-brazil** [comment]
This is updated now.

**Pull request merged**
