### PR TITLE
PEP8 fixes

### PR DESCRIPTION
**Pull request by mmoya**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Shouldn't it be a 4 space indent for pep8?

**Comment by mmoya** [comment]
I prefer 4 spaces but I thought it would be too intrusive. Would resubmit the PR adding that change.

**Comment by brian-brazil** [comment]
We can do that as a separate change then. Can you squash down the commits?

**Comment by mmoya** [comment]
Merged the two pep8 related commits.

**Comment by juliusv** [comment]
@mmoya Woot, thanks!

**Pull request merged**
