### PR TITLE
Add UntypedMetricFamily to prometheus_client.core

### PR DESCRIPTION
**Pull request by idsvandermolen**
I thought this one was missing from prometheus_client.core, so that's why I propose to add it. But their may be a reason why it wasn't added in the first place.

### CODE REVIEW

**Comment by brian-brazil** [comment]
It's more that noone has asked. Can you add a unittest please?

**Comment by idsvandermolen** [comment]
sure, I'll have a look.

**Comment by idsvandermolen** [comment]
I hope that covers it.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
