### PR TITLE
Rename extras_requires to extras_require

### PR DESCRIPTION
**Pull request by mrueg**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you expand on the reason for this change?

**Comment by mrueg** [comment]
There's no keyword called extras_requires in setuptools. See http://setuptools.readthedocs.io/en/latest/setuptools.html

**Comment by brian-brazil** [comment]
Thanks!

That's wonderfully inconsistent.

**Comment by mrueg** [comment]
Well extras is plural, so it makes sense to drop the s. Still I agree for consistency reasons it would have been a better choice to call it extra_requires

**Pull request merged**
