### PR TITLE
Clean up the ProcessCollector.

### PR DESCRIPTION
**Pull request by vad**
Code:
- remove unused imports
- remove a useless try/except/raise that wraps a os.path.join()

Style:
- max line length 119
- use 4 spaces for indentation
- fix indentation of continuation lines

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks. Would you mind adding a small unittest for the missing file?

**Comment by vad** [comment]
So you confirm that "return silently" is the behaviour you expect?

**Comment by vad** [comment]
Ok, I'll write the test ASAP, probably today

**Comment by vad** [comment]
Ok, in the end I looked at this only today and reverted to the old behaviour. The try/except was not around open() but around os.path.join(). IMHO it makes totally sense to raise and exception in this case, because it's probably an error in self._pid()

**Comment by brian-brazil** [comment]
Can you squash your commits and update the description?

**Comment by vad** [comment]
@brian-brazil is it ok?

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
