### PR TITLE
Use `ujson` as option for JSON processing

### PR DESCRIPTION
**Pull request by umax**
Hi!

The next one is about using high performance [json](https://github.com/esnme/ultrajson) library _ujson_ (as option).

### CODE REVIEW

**Comment by brian-brazil** [comment]
I avoid dependencies in this module, so I'd prefer not to add one if it isn't strictly needed.

**Comment by umax** [comment]
This dependency is optional, when you install package like `pip install prometheus_client`, standard _json_ package will be used. I think, _ujson_ has a chance to be optional dependency for those, who really need high performance. _ujson_ is much faster than standard _json_:
```
In [4]: %timeit json.dumps(('name', (('l1', 'v1'), ('l2', 'v2')), 123))
3.85 µs ± 115 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [5]: %timeit ujson.dumps(('name', (('l1', 'v1'), ('l2', 'v2')), 123))
839 ns ± 13.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**Comment by brian-brazil** [comment]
From a support and maintenance standpoint I'd prefer to not have two different ways that users could be running things. I'd not be against doing something more custom if it's faster, I only use json for convenience.

**Comment by umax** [comment]
I understand you, the more dependencies brings, the more unpredictable code is going to be. But for Python world it's common practice to try to use fast C implementations for different libraries instead of standard ones if it brings significant speed up.

I'd not propose these changes, but samples aggregation works slow for a huge dataset, that is why I'm trying to speed up it where possible. _ujson_ is stable for a long time and has a lot of tests. Again, _ujson_ set as optional.

So, it's up to you to merge these changes or not. In any way, thanks for quick reply and responsibility.

**Comment by brian-brazil** [comment]
The json in CPython has been a fast C implementation for quite a long time now.

**Comment by umax** [comment]
http://artem.krylysov.com/blog/2015/09/29/benchmark-python-json-libraries/

**Comment by brian-brazil** [comment]
I'm not willing to take this particular change, but I am open to not using JSON.

**Pull request closed without merging**
