### PR TITLE
Fix instance_ip_grouping_key not working on macOS

### LINKED ISSUE #629: `instance_ip_grouping_key` does not work on macOS
macOS 11.1
Python 3.8.5
prometheus-client 0.9.0

To reproduce:
```python
from prometheus_client import instance_ip_grouping_key

instance_ip_grouping_key()
```

What happens?
```
metrics.py:10: in <module>
    INSTANCE = instance_ip_grouping_key()
lib/python3.8/site-packages/prometheus_client/exposition.py:379: in instance_ip_grouping_key
    s.connect(('localhost', 0))
E   OSError: [Errno 49] Can't assign requested address
```

### PR DESCRIPTION
**Pull request by AceFire6**
Fixes #629

The solution is adapted from this StackOverflow answer: https://stackoverflow.com/a/28950776

@csmarchbanks I decided I'd just make the PR so long and if the solution isn't acceptable it can just be closed 👍

### CODE REVIEW

**Comment by csmarchbanks** [comment]
Thank you for the PR, I just got back from a couple weeks of vacation, and will take a look at this soon. Just need to make sure I fully understand the workaround.

**Review by csmarchbanks — COMMENTED** [review]
I apologize for the delay. I spent some time testing this, and my main concern is that it looks like the result could be different  with this change. E.g. on my local machine `instance_ip_grouping_key()` changes from `{'instance': '127.0.0.1'}` to `{'instance': '192.168.1.107'}`. For many cases the new result probably makes more sense, but this could be a breaking change if someone is configuring their servers with a specific IP address.

**Comment by AceFire6** [comment]
Ah okay. That isn't good!

I wasn't really sure how to test it and we didn't end up using the patch upstream as we had intended to when I made this PR.

I guess this doesn't fit the bill then. I'm not really sure where to go from here so I guess I'll leave what happens next up to you.

Thanks for the review 👍

**Comment by csmarchbanks** [comment]
One option would be to check if the platform is Darwin and use your new version in that case, but keep the old behavior for all other platforms? If there is a comment for why the two are handled slightly differently I would be happy moving forward with that.

**Comment by AceFire6** [comment]
@csmarchbanks Cool, I can change the PR to do that 👍

**Comment by AceFire6** [comment]
@csmarchbanks I've made the change to choose which method is used based on the platform 👍

**Pull request merged**
