### PR TITLE
multiprocess: don't crash on missing gauge_live/sum files

### LINKED ISSUE #425: MultiProcessCollector.collect() crashing on missing files
Hello,

When you've used a lot of pids and have a lot of metrics files lying around, there is a high probability that `mark_process_dead` 
https://github.com/prometheus/client_python/blob/8a4f2deec5ea90a65465171dddf7c576e2e23188/prometheus_client/multiprocess.py#L140-L147
 will be called between the `glob.glob` call and the `self.merge` one:
https://github.com/prometheus/client_python/blob/8a4f2deec5ea90a65465171dddf7c576e2e23188/prometheus_client/multiprocess.py#L136-L137

leading to:

```
$ prometheus_multiproc_dir=/tmp/prometheus_metrics python
Python 3.7.3 (default, May  8 2019, 05:31:59)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from prometheus_client import multiprocess
>>> from prometheus_client import generate_latest, CollectorRegistry
>>> registry = CollectorRegistry()
>>> multiprocess.MultiProcessCollector(registry)
<prometheus_client.multiprocess.MultiProcessCollector object at 0x7ffb0b1efa58>
>>> data = generate_latest(registry)
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/home/grocker/app.venv/lib/python3.7/site-packages/prometheus_client/exposition.py", line 89, in generate_latest
   for metric in registry.collect():
 File "/home/grocker/app.venv/lib/python3.7/site-packages/prometheus_client/registry.py", line 75, in collect
   for metric in collector.collect():
 File "/home/grocker/app.venv/lib/python3.7/site-packages/prometheus_client/multiprocess.py", line 30, in collect
   return self.merge(files, accumulate=True)
 File "/home/grocker/app.venv/lib/python3.7/site-packages/prometheus_client/multiprocess.py", line 43, in merge
   d = MmapedDict(f, read_mode=True)
 File "/home/grocker/app.venv/lib/python3.7/site-packages/prometheus_client/mmap_dict.py", line 39, in __init__
   self._f = open(filename, 'rb' if read_mode else 'a+b')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/prometheus_metrics/gauge_livesum_37367.db'
```
An easy fix could be #424.

### PR DESCRIPTION
**Pull request by xavfernandez**
Closes #425

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks, there's a test failure.

**Comment by xavfernandez** [comment]
> Thanks, there's a test failure.

Yes, it is apparently failing in master too: https://travis-ci.org/prometheus/client_python/builds/542696662 
I've opened #427 for it.

**Comment by xavfernandez** [comment]
With #428 merged, all tests now pass.

**Comment by brian-brazil** [comment]
Thanks!

**Comment by xavfernandez** [comment]
> Thanks!

No problem, thanks for your work :)
Any chance for a patch release ? Or any idea when the next minor will be released ?

**Comment by brian-brazil** [comment]
I'll have a better idea this evening after the OpenMetrics meeting.

**Comment by xavfernandez** [comment]
> I'll have a better idea this evening after the OpenMetrics meeting.

How did it go ? :grinning:

**Comment by brian-brazil** [comment]
We didn't discuss the relevant point, so I've put a release on my todo list.

**Pull request merged**
