### PR TITLE
Make registry optional for MultiProcessCollector

### PR DESCRIPTION
**Pull request by marksteward**
@brian-brazil this is a trivial first PR to make it possible to make it easier to add more collectors during a multiproc scrape. This is so the pattern eventually can be:

```
    registry = CollectorRegistry()
    registry.register(MultiProcessCollector())
    registry.register(PlatformCollector())
    # add your own CustomCollectors here
```

instead of having to explicitly pass None to each Collector.

I would also have included the change for PlatformCollector, but I'm concerned that might break existing code. Should it be accompanied by deprecation warnings, or is it not worth doing?

### CODE REVIEW

**Comment by brian-brazil** [comment]
> I would also have included the change for PlatformCollector, but I'm concerned that might break existing code. 

What is there to change?

**Comment by brian-brazil** [comment]
It's usually expected that you will pass the registry to a collector, rather than having to register it yourself. I'm not sure what you are proposing is actually saving code.

**Comment by marksteward** [comment]
> What is there to change?

To make PlatformCollector default to not registering itself with the default registry, except for the default instance. So:

```
    def __init__(self, registry=None, platform=None):
...
PLATFORM_COLLECTOR = PlatformCollector(core.REGISTRY)
```

This is more explicit and means someone creating their own PlatformCollector doesn't end up with one already registered by accident.

**Comment by marksteward** [comment]
> It's usually expected that you will pass the registry to a collector, rather than having to register it yourself. I'm not sure what you are proposing is actually saving code.

This wasn't clear. The README has:

```
REGISTRY.register(CustomCollector())
```

but then:

```
    multiprocess.MultiProcessCollector(registry)
```

When I first looked at this, I assumed MultiProcessCollector was doing some sort of quirky transformation on the registry, rather than just registering itself.

My hope is to make multiproc more self-explanatory and fit better with patterns used in Django, Flask, etc.

**Comment by marksteward** [comment]
I'll raise a separate PR to improve the README.

**Pull request closed without merging**
