### PR TITLE
Unbundle decorator

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
We purposefully avoid dependencies in the core. Is this causing you an issue?

**Comment by ignatenkobrain** [comment]
I can definitely carry this patch downstream in Fedora, but why dependenices are a problem?

**Comment by brian-brazil** [comment]
It increases the risk of versioning conflicts etc. I want this library to be as risk free to use as practical.

**Comment by brian-brazil** [comment]
This has gone stale, and I don't see a need for this change.

**Pull request closed without merging**
