### PR TITLE
Rename choose_formatter back to choose_encoder

### PR DESCRIPTION
**Pull request by csmarchbanks**
Other libraries depend on this function and we did not mean to create a breaking change. Add a test to document that this is part of the API.

Fixes https://github.com/prometheus/client_python/issues/795

### CODE REVIEW

**Comment by Starkteetje** [comment]
Note that this renaming is again a breaking change. If you want to avoid it, you could define one of the names as an alias to the other to get backwards-compatibility with the prior versions and 0.14 (though that's obviously ugly)

**Comment by Starkteetje** [comment]
Note that this renaming is again a breaking change. If you want to avoid it, you could define one of the names as an alias to the other to get backwards-compatibility with the prior versions and 0.14 (though that's obviously ugly)

**Comment by csmarchbanks** [comment]
Yeah, that is the case and I would prefer not to maintain the second function name forever. I am hoping that most people who are pinning versions are either pinning both or will upgrade to the patch version fairly quickly. Since the release has only been out for three days a bugfix to revert to the previous behavior seems reasonable to me?

**Comment by csmarchbanks** [comment]
To avoid the second breaking change in 0.14.x I added choose_formatter back in with a deprecation notice. It will be removed as part of 0.15, but that at least gives everyone some time to use either.

**Pull request merged**
