### PR TITLE
start_http_server for any given registry or the default registry

### PR DESCRIPTION
**Pull request by danni-m**
I'm using start_http_server, but unfortunately it only exposes the default registry, all other exposition methods have a registry parameter.

@brian-brazil

### CODE REVIEW

**Comment by brian-brazil** [comment]
You should only ever be exposing the default registry via this method. If you're doing something funky (such as what the snmp or blackbox exporters do), you'll need custom handling anyway.

**Comment by danni-m** [comment]
What I want is to expose 2 different registries on 2 different ports.
start_wsgi_server allows to receive a specific registry while start_http_server doesn't.

How those 2 functions differ except WSGI/SimpleHTTPServer ?

**Comment by brian-brazil** [comment]
> What I want is to expose 2 different registries on 2 different ports.

Why do you want to do this?

A single process should have a single registry.

**Comment by danni-m** [comment]
Is there any reason why `start_wsgi_server` should be different than `start_http_server`?

**Comment by brian-brazil** [comment]
There isn't, that parameter should be removed.

**Comment by danni-m** [comment]
@brian-brazil would you accept a PR that removes the parameter?

**Comment by brian-brazil** [comment]
I would.

**Pull request closed without merging**
