### PR TITLE
Convert CI to CircleCI

### PR DESCRIPTION
**Pull request by SuperQ**
Replace Travis with CircleCI.
* Update Python version list.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
This doesn't seem to be doing quite the same thing. Some supported versions have been lost from testing, and we're no longer testing that things still work when none of the optional modules are installed.

**Comment by SuperQ** [comment]
Some of those old versions aren't supported by CircleCI (2.6, 3.4 for example).

**Comment by brian-brazil** [comment]
There's a 3.4: https://hub.docker.com/layers/circleci/python/3.4/images/sha256-6403a42dff13d3593b541f75bb695584b5d6695675a4a1d1b2773081ede22e05?context=explore

It might be finally time to drop 2.6.

**Comment by SuperQ** [comment]
I was trying to go directly to CircleCI's "next gen" images.

**Comment by brian-brazil** [comment]
If we're dropping versions, then setup.py needs updating.

**Comment by SuperQ** [comment]
I re-added Python 3.4 support.

**Comment by brian-brazil** [comment]
:+1:

**Pull request merged**
